name: smileline_monitoring
description: "App companion per allineatori invisibili"
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  url_launcher: ^6.2.0
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0

  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  permission_handler: ^11.0.0

  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1

  shared_preferences: ^2.2.0
  workmanager: ^0.7.0
  flutter_foreground_task: ^8.1.0
  flutter_local_notifications: ^19.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.0


  timezone: ^0.10.1

  flutter_animate: ^4.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.0

  intl: ^0.19.0
  uuid: ^4.0.0
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0

  table_calendar: ^3.0.0

  pdf: ^3.10.0
  printing: ^5.11.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/illustrations/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


